### ISSUE TITLE
Feature Request/Bug Report: Add sub ids and water/lava logging

### ISSUE THREAD

**Issue by ghost** [NoahBPeterson/BlockTrack#1]
You don't save the sub id of the block in the db. And the BlockPlace- or BlockBreakEvent doesn't trigger, if lava or water is placed (maybe use BucketFill- and BucketEmptyEvent).

**Comment by ghost** [comment]
And please add permissions to the commands.

**Comment by NoahBPeterson** [comment]
Done, done, and done.

**Comment by ghost** [comment]
Thanks, thanks and thanks! xD
